kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "python-webapp-pipeline"
spec:
  source:
    git: 
     uri: https://github.com/JTG2020/python-webapp.git
     ref: openshift
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: .
    type: JenkinsPipeline 