apiVersion: v1
kind: ConfigMap
metadata:
  name: python-webapp-config
  labels:
    app: python-webapp-config
data:
  NAME: This message is from configmap - Hello kubernetes !
  BGCOLOR: yellow

---

kind: Service
apiVersion: v1
metadata:
  name:  python-webapp-svc
spec:
  selector:
    app:  python-webapp
  type:  NodePort
  ports:
  - name:  http
    port:  9000
    targetPort:  9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp-deployment
spec:
  selector:
    matchLabels:
      app: python-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: hello-python
        image: docuser200/python-webapp:1.0.0
        ports:
        - containerPort: 9000
        envFrom:
          - configMapRef:
             name: python-webapp-config
