kind: Service
apiVersion: v1
metadata:
  name:  redis
spec:
  selector:
    app:  python-redis-app
  type:  ClusterIP
  ports:
  - protocol:  TCP
    port:  6379
    targetPort:  6379

---

    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-redis-app
    spec:
      selector:
        matchLabels:
          app: python-redis-app
      replicas: 1
      template:
        metadata:
          labels:
            app: python-redis-app
        spec:
          containers:
          - name: python-redis
            image: 127.0.1.1:7502/redis:5.0.3-alpine 
            ports:
            - containerPort: 6379   
